# Generated by Django 4.0.1 on 2024-04-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostTitulo', models.CharField(max_length=100)),
                ('PostDescripcion', models.TextField()),
                ('PostPortada', models.ImageField(upload_to='post/images/')),
                ('PostFechaCreacion', models.DateField()),
            ],
        ),
    ]
