# Generated by Django 4.0.1 on 2024-04-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0001_initial'),
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PostCategoriaId',
            field=models.ForeignKey(db_column='PostCategoriaId', default=1, on_delete=django.db.models.deletion.CASCADE, to='Categoria.categoria'),
        ),
        migrations.AddField(
            model_name='post',
            name='PostContenido',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='PostFechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
