# Generated by Django 4.0.1 on 2024-04-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estacionamiento', '0005_estacionamiento_estestado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlazaNumero', models.IntegerField()),
                ('PlazaEstado', models.BooleanField(default=True)),
                ('PlazaEstUbicacion', models.ForeignKey(db_column='PlazaEstUbicacion', on_delete=django.db.models.deletion.CASCADE, to='Estacionamiento.estacionamiento', to_field='EstUbicacion')),
            ],
        ),
    ]
