# Generated by Django 4.0.1 on 2024-04-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plaza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionPlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlazaNumero', models.IntegerField()),
                ('PlazaEstUbicacion', models.CharField(max_length=100)),
                ('PlazaEstado', models.CharField(max_length=20)),
                ('PlazaFechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreacionPlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlazaNumero', models.IntegerField()),
                ('PlazaEstUbicacion', models.CharField(max_length=100)),
                ('PlazaFechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EliminacionPlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlazaNumero', models.IntegerField()),
                ('PlazaEstUbicacion', models.CharField(max_length=100)),
                ('PlazaFechaEliminacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
