# Generated by Django 4.0.1 on 2024-04-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estacionamiento', '0008_remove_estacionamiento_estempresanombre_and_more'),
        ('Plaza', '0002_actualizacionplaza_creacionplaza_eliminacionplaza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacionplaza',
            name='PlazaEstUbicacion',
        ),
        migrations.RemoveField(
            model_name='creacionplaza',
            name='PlazaEstUbicacion',
        ),
        migrations.RemoveField(
            model_name='eliminacionplaza',
            name='PlazaEstUbicacion',
        ),
        migrations.RemoveField(
            model_name='plaza',
            name='PlazaEstUbicacion',
        ),
        migrations.AddField(
            model_name='actualizacionplaza',
            name='PlazaEstId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='creacionplaza',
            name='PlazaEstId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eliminacionplaza',
            name='PlazaEstId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plaza',
            name='PlazaEstId',
            field=models.ForeignKey(db_column='PlazaEstId', default=1, on_delete=django.db.models.deletion.CASCADE, to='Estacionamiento.estacionamiento'),
        ),
    ]
