# Generated by Django 4.0.1 on 2024-04-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plaza', '0003_remove_actualizacionplaza_plazaestubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionplaza',
            name='PlazaEstId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creacionplaza',
            name='PlazaEstId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eliminacionplaza',
            name='PlazaEstId',
            field=models.CharField(max_length=100),
        ),
    ]
