# Generated by Django 4.0.1 on 2024-04-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plaza', '0004_alter_actualizacionplaza_plazaestid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionplaza',
            name='PlazaEstId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creacionplaza',
            name='PlazaEstId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eliminacionplaza',
            name='PlazaEstId',
            field=models.IntegerField(),
        ),
    ]
