# Generated by Django 4.0.1 on 2024-04-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0003_alter_empresa_empresanombre'),
        ('Estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='EstacionamientoEmpresaNombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa', to_field='EmpresaNombre'),
        ),
    ]
