# Generated by Django 4.0.1 on 2024-04-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0004_rename_empresaasunto_empresa_empasunto_and_more'),
        ('Estacionamiento', '0003_rename_estacionamientocapacidadactual_estacionamiento_estcapacidadactual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='EstEmpresaNombre',
            field=models.ForeignKey(db_column='EstEmpresaNombre', on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa', to_field='EmpNombre'),
        ),
    ]
