# Generated by Django 4.0.1 on 2024-04-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estacionamiento', '0004_alter_estacionamiento_estempresanombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='EstEstado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='EstUbicacion',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
