# Generated by Django 4.0.1 on 2024-04-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estacionamiento', '0005_estacionamiento_estestado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstUbicacion', models.CharField(max_length=100)),
                ('EmpModificacion', models.TextField(default='')),
                ('EmpFechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreacionEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstUbicacion', models.CharField(max_length=100)),
                ('EmpFechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EliminacionEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstUbicacion', models.CharField(max_length=100)),
                ('EmpFechaEliminacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='EstCapacidadActual',
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='EstCapacidadMaxima',
        ),
    ]
