# Generated by Django 4.0.1 on 2024-04-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estacionamiento', '0006_actualizacionestacionamiento_creacionestacionamiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualizacionestacionamiento',
            old_name='EmpFechaActualizacion',
            new_name='EstFechaActualizacion',
        ),
        migrations.RenameField(
            model_name='actualizacionestacionamiento',
            old_name='EmpModificacion',
            new_name='EstModificacion',
        ),
        migrations.RenameField(
            model_name='creacionestacionamiento',
            old_name='EmpFechaCreacion',
            new_name='EstFechaCreacion',
        ),
        migrations.RenameField(
            model_name='eliminacionestacionamiento',
            old_name='EmpFechaEliminacion',
            new_name='EstFechaEliminacion',
        ),
    ]
