# Generated by Django 4.0.1 on 2024-04-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0010_alter_actualizacionempresa_empfechaactualizacion_and_more'),
        ('Estacionamiento', '0007_rename_empfechaactualizacion_actualizacionestacionamiento_estfechaactualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamiento',
            name='EstEmpresaNombre',
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='EstEmpresaId',
            field=models.ForeignKey(db_column='EstEmpresaId', default=1, on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa'),
        ),
    ]
