# Generated by Django 4.0.1 on 2024-04-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estacionamiento', '0008_remove_estacionamiento_estempresanombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacionestacionamiento',
            name='EstId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='creacionestacionamiento',
            name='EstId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eliminacionestacionamiento',
            name='EstId',
            field=models.IntegerField(default=1),
        ),
    ]
