# Generated by Django 4.0.1 on 2024-04-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='EmpresaEstado',
            field=models.BooleanField(default=False),
        ),
    ]
