# Generated by Django 4.0.1 on 2024-04-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0003_alter_empresa_empresanombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='EmpresaAsunto',
            new_name='EmpAsunto',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='EmpresaCorreo',
            new_name='EmpCorreo',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='EmpresaDNICreador',
            new_name='EmpDNICreador',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='EmpresaDescripcion',
            new_name='EmpDescripcion',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='EmpresaDireccionPrincipal',
            new_name='EmpDireccionPrincipal',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='EmpresaEstado',
            new_name='EmpEstado',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='EmpresaNombre',
            new_name='EmpNombre',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='EmpresaNombreCreador',
            new_name='EmpNombreCreador',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='EmpresaRUC',
            new_name='EmpRUC',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='EmpresaTelefono',
            new_name='EmpTelefono',
        ),
    ]
