# Generated by Django 4.0.1 on 2024-04-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0004_rename_empresaasunto_empresa_empasunto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpNombre', models.CharField(max_length=100, unique=True)),
                ('EmpFechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='EmpEstado',
            field=models.BooleanField(default=True),
        ),
    ]
