# Generated by Django 4.0.1 on 2024-04-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0005_creacionempresa_alter_empresa_empestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpNombre', models.CharField(max_length=100, unique=True)),
                ('EmpFechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EliminacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpNombre', models.CharField(max_length=100, unique=True)),
                ('EmpFechaEliminacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
