# Generated by Django 4.0.1 on 2024-04-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0006_actualizacionempresa_eliminacionempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionempresa',
            name='EmpNombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creacionempresa',
            name='EmpNombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eliminacionempresa',
            name='EmpNombre',
            field=models.CharField(max_length=100),
        ),
    ]
