# Generated by Django 4.0.1 on 2024-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0007_alter_actualizacionempresa_empnombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacionempresa',
            name='EmpModificacion',
            field=models.TextField(default=''),
        ),
    ]
