# Generated by Django 4.0.1 on 2024-04-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0008_actualizacionempresa_empmodificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionempresa',
            name='EmpFechaActualizacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creacionempresa',
            name='EmpFechaCreacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eliminacionempresa',
            name='EmpFechaEliminacion',
            field=models.CharField(max_length=50),
        ),
    ]
