# Generated by Django 4.0.1 on 2024-04-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0009_alter_actualizacionempresa_empfechaactualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacionempresa',
            name='EmpFechaActualizacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='creacionempresa',
            name='EmpFechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eliminacionempresa',
            name='EmpFechaEliminacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
