# Generated by Django 4.0.1 on 2024-04-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0010_alter_actualizacionempresa_empfechaactualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacionempresa',
            name='EmpId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='creacionempresa',
            name='EmpId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eliminacionempresa',
            name='EmpId',
            field=models.IntegerField(default=1),
        ),
    ]
